# Generated by Django 4.2.4 on 2023-08-13 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tag_tagscope_tag_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TagScope',
            new_name='Relationship',
        ),
    ]
