# Generated by Django 4.2.4 on 2023-08-13 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_tagscope_relationship'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Object',
        ),
    ]
